### PR TITLE
Feature commands edit command

### PR DESCRIPTION
**Pull request by Bisceto**
Fixed test case for editing specific fields of a food item.

### CODE REVIEW

**Review by Jnjy — CHANGES_REQUESTED** [review]
just a minor change, other than that LGTM

**Review by ScorpiusSigma — CHANGES_REQUESTED** [review]
Run checkstyle and push again

**Review by ScorpiusSigma — APPROVED** [review]
LGTM

**Review by Jnjy — APPROVED** [review]
LGTM

**Pull request merged**
